title: CV | James Addis
description: A beautiful template for your CV.
destination: ./public
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-minifier

exclude:
  # ruby files
  - Gemfile
  - Gemfile.lock
  
  # docker
  - docker-compose.yml
  - docker-compose.actions.yml
  - Dockerfile
  - .dockerignore
  - .env # default environment variables for docker compose

  # node js files
  - node_modules/
  - package.json
  - package-lock.json

  # github
  - .github/
  - .gitignore
  - README.md
  - preview.png
  - LICENSE

  # output folder
  - artifacts/
# security headers
webrick:
  headers:
    "X-XSS-Protection": "1; mode=block"
    "X-Frame-Options": "DENY"
    "X-Content-Type-Options": "nosniff"
    Content-Security-Policy: >
      default-src 'self'; 
      font-src 'self' https://cdnjs.cloudflare.com; 
      script-src 'self' https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js; 
      style-src 'self' https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css; 
      img-src 'self';
      media-src 'self';
      object-src 'none';
      worker-src 'self';
      base-uri 'self';
      frame-src 'none';
      frame-ancestors 'none';
      sandbox allow-scripts allow-presentation allow-same-origin;